### PR TITLE
add options -f and -c, refactor imports

### PR DESCRIPTION
**Pull request by aparcar**
option -f is for sending and yaml creating, forcing to do something what
should normally only be once, like sending an invoice or createing an
invoice based on the contract information

option -c wants a cid to perform a creation or send on a single contract
id instead of all.

both options can be combined

instead of using from .invoice import * now uses import rechnung.invoice
which allows further refactoring and resolves name conflicts in the cli

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by olf42** [comment]
Ok, I just adapted the test to represent the changes, yet the improvements (force-options, and single recreation/send option) should be covered by tests before merging.

**Comment by aparcar** [comment]
I'll remove the slug settings from this PR

**Comment by olf42** [comment]
Interesting, ... `$ make test` works on my machine, but  fails here...

**Review by olf42 — APPROVED** [review]
Added tests for --force-recreate and --cid-only of the create-invoices command.

**Pull request merged**
